# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TT_Layout2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(539, 507)
        MainWindow.setMinimumSize(QtCore.QSize(539, 507))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 0, 241, 61))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 60, 521, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 120, 131, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 151, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 80, 91, 31))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(210, 120, 131, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 170, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(70, 220, 381, 221))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(410, 80, 60, 31))
        self.label_4.setObjectName("label_4")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(380, 120, 121, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600; color:#e20110;\">Data entry</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; text-decoration: underline;\">Teacher\'s Name</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; text-decoration: underline;\">Subject</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "SUBJECT"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Math"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Socials"))
        self.comboBox.setItemText(3, _translate("MainWindow", "P.E"))
        self.comboBox.setItemText(4, _translate("MainWindow", "English"))
        self.comboBox.setItemText(5, _translate("MainWindow", "3rd Language"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Music/Dance"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Chemistry"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Physics"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Biology"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Others"))
        self.pushButton.setText(_translate("MainWindow", "Update List"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "sfg"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "dzfgadfgdf"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "gadf"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "gad"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "fg"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "adfg"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "adfg"))
        item = self.listWidget.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "daf"))
        item = self.listWidget.item(9)
        item.setText(_translate("MainWindow", "g"))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "ad"))
        item = self.listWidget.item(11)
        item.setText(_translate("MainWindow", "fg"))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", "ad"))
        item = self.listWidget.item(13)
        item.setText(_translate("MainWindow", "fg"))
        item = self.listWidget.item(14)
        item.setText(_translate("MainWindow", "as"))
        item = self.listWidget.item(15)
        item.setText(_translate("MainWindow", "df"))
        item = self.listWidget.item(16)
        item.setText(_translate("MainWindow", "asd"))
        item = self.listWidget.item(17)
        item.setText(_translate("MainWindow", "f"))
        item = self.listWidget.item(18)
        item.setText(_translate("MainWindow", "asdfg"))
        item = self.listWidget.item(19)
        item.setText(_translate("MainWindow", "adfgad"))
        item = self.listWidget.item(20)
        item.setText(_translate("MainWindow", "f"))
        item = self.listWidget.item(21)
        item.setText(_translate("MainWindow", "ok bye"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; text-decoration: underline;\">Class</span></p></body></html>"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1A"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "1B"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "1C"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "2A"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "2B"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "2C"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "3A"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "3B"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "3C"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "4A"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "4B"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "4C"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "5A"))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "5B"))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "5C"))
        self.comboBox_2.setItemText(15, _translate("MainWindow", "6A"))
        self.comboBox_2.setItemText(16, _translate("MainWindow", "6B"))
        self.comboBox_2.setItemText(17, _translate("MainWindow", "6C"))
        self.comboBox_2.setItemText(18, _translate("MainWindow", "7A"))
        self.comboBox_2.setItemText(19, _translate("MainWindow", "7B"))
        self.comboBox_2.setItemText(20, _translate("MainWindow", "7C"))
        self.comboBox_2.setItemText(21, _translate("MainWindow", "8A"))
        self.comboBox_2.setItemText(22, _translate("MainWindow", "8B"))
        self.comboBox_2.setItemText(23, _translate("MainWindow", "8C"))
        self.comboBox_2.setItemText(24, _translate("MainWindow", "9A"))
        self.comboBox_2.setItemText(25, _translate("MainWindow", "9B"))
        self.comboBox_2.setItemText(26, _translate("MainWindow", "9C"))
        self.comboBox_2.setItemText(27, _translate("MainWindow", "10A"))
        self.comboBox_2.setItemText(28, _translate("MainWindow", "10B"))
        self.comboBox_2.setItemText(29, _translate("MainWindow", "10C"))
        self.comboBox_2.setItemText(30, _translate("MainWindow", "11A"))
        self.comboBox_2.setItemText(31, _translate("MainWindow", "11B"))
        self.comboBox_2.setItemText(32, _translate("MainWindow", "12A"))
        self.comboBox_2.setItemText(33, _translate("MainWindow", "12B"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

